name: My First GitHub Actions

on:
    push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: multiple steps into a single step
              run: |
                echo "This is my 1st Workflow"
                ls
                cat README.md
