name: My First GitHub Actions

on:
    push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Welcome Message
              run: echo "This is my 1st Workflow"
            
            - name: List Files
              run: ls

            - name: Read File
              run: cat README.md
