name: Generate ASCII

on:
    push

jobs:
    ascii_job:

      runs-on: ubuntu-latest
      steps:

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Generate sheep
        run: cowsay -f sheep "Baa... CI/CD is running!" >> sheep.txt

      - name: Test file exist
        run: grep -i "sheep" sheep.txt || true

      - name: Read file
        run: cat sheep.txt

      - name: List files
        run: ls -ltra