name: Generate ASCII

on:
    push

jobs:
    ascii_job:

      runs-on: ubuntu-latest
      steps:

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Generate dragon
        run: cowsay -f dragon "Baa... CI/CD is running!" >> dragon.txt

      - name: Test file exist
        run: grep -i "dragon" dragon.txt || true

      - name: Read file
        run: cat dragon.txt

      - name: List files
        run: ls -ltra