name: Matrix Configuration

on:
 push:
 workflow_dispatch:

jobs:
    deploy:
        strategy:
            matrix:
              os: [ubuntu-latest, windows-latest]
              images: [hello-world, alpine]
        runs-on: ${{matrix.os }}
        steps:
        - name: Echo Docker Details
          run: docker info
          
        - name: Docker ${{matrix.images}}
          run: docker run ${{matrix.images}}


        